# Generated by Django 3.2.4 on 2021-08-01 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20210801_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabungan',
            name='user',
        ),
        migrations.AddField(
            model_name='pinjaman',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pinjaman',
            name='nama',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tabungan',
            name='nama',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
