# Generated by Django 3.2.4 on 2021-08-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210805_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldoawal',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='saldoawal',
            name='Month',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
