# Generated by Django 3.2.4 on 2021-08-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210808_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldoawal',
            old_name='Month',
            new_name='month',
        ),
    ]
