# Generated by Django 3.2.4 on 2021-08-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_pengeluaran_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengeluaran',
            name='month',
        ),
    ]
