# Generated by Django 3.2.4 on 2021-08-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_pengeluaran_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengeluaran',
            name='nama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
    ]
