# Generated by Django 3.2.4 on 2021-08-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bayar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bayar',
            old_name='tanggal',
            new_name='tanggal1',
        ),
    ]
